### PR TITLE
fix: output functions with cjs extension to be independent of site module type

### LINKED ISSUE #1194: [Bug]: IPX fails with `type: module` in package.json
### Summary

This bug has been filed as a response to the ticket: https://netlify.zendesk.com/agent/tickets/82173 (internal only).

The user has a monorepo with the following `package.json`:

<details>
  <summary>Monorepo package.json</summary>

```json
{
  "name": "5starz",
  "version": "1.0.0",
  "license": "MIT",
  "type": "module",
  "engines": {
    "node": ">=16.0.0"
  },
  "dependencies": {
    "prettier": "^2.4.1",
    "ts-node": "^10.4.0",
    "typescript": "^4.5.2"
  },
  "devDependencies": {
    "@netlify/plugin-nextjs": "^4.2.2",
    "@types/lodash": "^4.14.177",
    "@types/node": "^16.11.9",
    "cross-env": "^7.0.3",
    "env-cmd": "^10.1.0",
    "tsc-watch": "^4.6.0"
  },
  "scripts": {
    "restart:backend": "docker build -f backend2/Dockerfile -t the5starz-backend:0.2.2 . && (cd deploy/compose/ && docker-compose down && docker-compose up -d)",
    "staging:check": "docker build -f backend2/Dockerfile -t the5starz-backend-staging:0.2.4 . && (cd deploy/staging/ && docker-compose down && docker-compose up)",
    "logs:backend": "cd ~/the5starz/deploy/compose && docker-compose logs",
    "build:front": "yarn workspace @the5starz/common build && yarn workspace front build",
    "build:website": "yarn workspace @the5starz/common build && yarn workspace website build",
    "build:backend": "yarn workspace @the5starz/common build && yarn workspace @the5starz/db generate && yarn workspace @the5starz/db build && yarn workspace backend2 build",
    "clean-npm": "yarn cache clean && rm -rf ./*/yarn.lock && rm -rf */package-lock.json && rm -rf yarn.lock && rm -rf package-lock.json && rm -rf ./*/node_modules/ && rm -rf node_modules",
    "test": "./node_modules/.bin/ts-node --transpile-only scripts/old/json-transform-test.ts",
    "get-s3-files": ""
  },
  "private": true,
  "workspaces": {
    "packages": [
      "db",
      "backend2",
      "front",
      "scripts",
      "common",
      "website",
      "apify"
    ]
  },
  "volta": {
    "node": "16.13.1",
    "yarn": "1.22.17",
    "npm": "8.2.0"
  }
}
```
</details>

Their Next.js website has the following package.json:

<details>
  <summary>Next.js `package.json`</summary>

```json
{
  "name": "website",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "storybook": "start-storybook -p 6006 -s ./public",
    "build-storybook": "build-storybook -s public"
  },
  "dependencies": {
    "@headlessui/react": "^1.4.2",
    "@heroicons/react": "^1.0.5",
    "@mdx-js/loader": "^1.6.22",
    "@next/mdx": "^12.0.10",
    "axios": "^0.25.0",
    "next": "12.0.7",
    "react": "17.0.2",
    "react-countup": "^6.1.0",
    "react-dom": "17.0.2",
    "react-grid-gallery": "^0.5.5",
    "react-hook-form": "^7.25.0",
    "react-icons": "^4.3.1",
    "react-player": "^2.9.0",
    "react-slick": "^0.28.1",
    "react-visibility-sensor": "^5.1.1",
    "slick-carousel": "^1.8.1"
  },
  "devDependencies": {
    "@babel/core": "^7.16.12",
    "@storybook/addon-actions": "^6.4.14",
    "@storybook/addon-essentials": "^6.4.14",
    "@storybook/addon-links": "^6.4.14",
    "@storybook/react": "^6.4.14",
    "autoprefixer": "^10.4.2",
    "babel-loader": "^8.2.3",
    "eslint": "8.6.0",
    "eslint-config-next": "12.0.7",
    "eslint-plugin-storybook": "^0.5.6",
    "postcss": "^8.4.5",
    "tailwindcss": "^3.0.13"
  }
}
```
</details>

The generated `_ipx.zip` is attached: [_ipx.zip](https://github.com/netlify/netlify-plugin-nextjs/files/8003090/_ipx.zip)

### Steps to reproduce

N/A

### A link to a reproduction repository

N/A

### Plugin version

4.2.2

### More information about your build

- [ ] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

_No response_

### Your netlify.toml file

N/A

### Your public/_redirects file

N/A

### Your `next.config.js` file

N/A

### Builds logs (or link to your logs)

https://app.netlify.com/sites/the5starz-website/deploys/61fa7a6e5c4d41000836be19

### Function logs

<details>
  <summary>Function logs (_ipx)</summary>
  
```json
{
  "errorType": "ReferenceError",
  "errorMessage": "module is not defined in ES module scope\nThis file is being treated as an ES module because it has a '.js' file extension and '/var/task/package.json' contains \"type\": \"module\". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.",
  "trace": [
    "ReferenceError: module is not defined in ES module scope",
    "This file is being treated as an ES module because it has a '.js' file extension and '/var/task/package.json' contains \"type\": \"module\". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.",
    "    at file:///var/task/_ipx.js:1:1",
    "    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)",
    "    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:60:5)",
    "    at /var/runtime/deasync.js:23:15",
    "    at _tryAwaitImport (/var/runtime/UserFunction.js:74:12)",
    "    at _tryRequire (/var/runtime/UserFunction.js:162:21)",
    "    at _loadUserApp (/var/runtime/UserFunction.js:197:12)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:242:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:1085:14)"
  ]
}
```
</details>

### .next JSON files

N/A

### LINKED ISSUE #1456: [Bug]: ESM not supported with Netlify functions? (part 2)
[https://github.com/netlify/next-runtime/issues/1456#issuecomment-1997058498](https://github.com/netlify/next-runtime/issues/1456#issuecomment-1997058498)

> But just to be absolutely clear, [Deploy Previews are currently using](https://github.com/netlify/next-runtime/issues/1456#issuecomment-1994377971) `[@5](https://github.com/netlify/next-runtime/issues/1456#issuecomment-1994377971)` which causes all deploys to fail for users who have opted in to the Next.js v5 Runtime. (both Deploy Previews on new pushes to branches and also regular deploys from new pushes to the main branch)
>
> So without my workaround, the opted-in Next.js v5 Runtime is unusable.

Looks like there are potential issues with deploy previews.

### PR DESCRIPTION
**Pull request by danez**
Part of netlify/pod-compute#149

Fixes #1456 
Fixes #1194 

### Summary

Outputs the functions with .cjs extension. Because of the recent changes to zip-it-and-ship-it the `cjs` extension will be kept and this in turn means that the functions are not affected by `type:module` in a sites `package.json`.

### Test plan

Tests pass

### Standard checks:

- [x] Check the Deploy Preview's Demo site for your PR's functionality
- [ ] Add docs when necessary

---

🧪 Once merged, make sure to update the version if needed and that it was published correctly.

### CODE REVIEW

**Comment by danez** [comment]
The test failures seem to be unrelated.

**Comment by sarahetter** [comment]
@danez Just checking on the status of this as I'm triaging the next-runtime board and this closes one of the issues there.

**Comment by danez** [comment]
Support for this was unfortunately never rolled out to customers. So this PR will not work. In the light that we are now building serverless functions v2 i do not think this will ever be rolled out and instead the new api will fix the root problem.

**Comment by MarcL** [comment]
Thanks, @danez. Can we close this PR for now then?

**Comment by gr2m** [comment]
> In the light that we are now reworking serverless functions, this might be fixed in a different way at some point.

can we follow the status on the rework of serverless functions? I ran into https://github.com/netlify/next-runtime/issues/1456#issuecomment-1579024210, it's currently blocking us from using Netlify

**Comment by orinokai** [comment]
@gr2m hopefully the new functions API should help with your issue? https://www.netlify.com/blog/introducing-netlify-functions-2-0/

**Comment by gr2m** [comment]
I am trying to deploy a next.js app, I am not writing functions manually. Do you know if the build setup for next.js apps is using the new functions?

**Comment by orinokai** [comment]
@gr2m ah, i see - so you're having trouble with your site that is defined as an ESM module? we have some upcoming improvements to the Next Runtime that should solve your problem - unfortunately i can't share dates at this stage, but it won't be too long

**Comment by karlhorky** [comment]
@orinokai @danez @sarahetter any chance of getting the fix published soon?

Or at least an officially-blessed workaround either here or in one of the other issues?

- #1456 
- #1194

**Comment by orinokai** [comment]
hi @karlhorky, we have made some improvements to the Next.js Runtime that will address this issue - it is currently being tested internally and we'll hopefully have some more information to share soon

**Comment by karlhorky** [comment]
@orinokai great, thanks for the update!

@ProchaLu and I can test this out when it's ready.

**Comment by karlhorky** [comment]
@orinokai is this fix contained in [the "Next.js Runtime v5" feature](https://docs.netlify.com/frameworks/next-js/overview/) that was just offered to me in early access?

I just saw this in my Netlify dashboard

Screenshot 2024-03-13 at 12 54 36

**Comment by ProchaLu** [comment]
@orinokai, Opt-in the [Next.js Runtime `v5`](https://docs.netlify.com/frameworks/next-js/overview/#prerequisites) (`@netlify/plugin-nextjs@5.0.0-rc.4`) resolved the issue. 

1. Re-deploying your Next.js application on Netlify
2. Opt-In to Next.js Runtime v5
    - After the re-deployment, navigate to the Deploys Section on Netlify
    - Look for the Opt-In button related to Next.js Runtime v5 and click it
3. During the deployment, you may encounter a warning about outdated plugins
```
1:56:31 PM: ❯ Outdated plugins
1:56:31 PM:    - @netlify/plugin-nextjs@4.41.3: latest version is 5.0.0-rc.4
1:56:31 PM:      To upgrade this plugin, please uninstall and re-install it from the Netlify plugins directory (https://app.netlify.com/plugins)
```
4. Remove and re-add Next.js Runtime under site configuration -> Build & deploy -> Build settings -> Configure -> Remove (next to Next.js) -> Save -> Configure -> Select -> Next.js

6. Trigger another re-deployment and the `@netlify/plugin-nextjs@5.0.0-rc.4` was added
```
1:58:59 PM: ❯ Installing plugins
1:58:59 PM:    - @netlify/plugin-nextjs@5.0.0-rc.4
```

**Pull request closed without merging**
