### PR TITLE
fix: Respect `pageExtensions` config setting

### PR DESCRIPTION
**Pull request by RohitRajendran**
### Summary

When using the [custom page extensions setting for Next.JS](https://nextjs.org/docs/api-reference/next.config.js/custom-page-extensions#including-non-page-files-in-the-pages-directory), you'll see errors during the onBuild event saying that it could not find the source file for your api routes. This causes things like scheduled functions not to work.

I've updated it so that it uses provided pageExtensions from the next config if available. If not, it will fallback to the previously used array for extensions.

### Test plan

1. It should be tested with a NextJS config that has page extensions settings defined as well as without

### Relevant links (GitHub issues, Notion docs, etc.) or a picture of cute animal

Fixes https://github.com/netlify/next-runtime/issues/2072.

image

### Standard checks:

- [ ] Check the Deploy Preview's Demo site for your PR's functionality

---

🧪 Once merged, make sure to update the version if needed and that it was published correctly.

### CODE REVIEW

**Review by LekoArts — APPROVED** [review]
Thanks 👍 

I added some unit tests to validate the behavior

**Comment by nickytonline** [comment]
Thanks for the PR @RohitRajendran!

**Comment by RohitRajendran** [comment]
Hey @nickytonline / @LekoArts! Just curious if you had any idea when I could expect the next release? Would love to be able to start using scheduled functions with my project! 😀

**Comment by orinokai** [comment]
Hey @RohitRajendran 👋🏼 this should now be fully rolled out. If you manually install the Next.js Runtime then you will need to update via NPM, otherwise the latest version should install during your next build. Thanks again for the PR!

**Comment by RohitRajendran** [comment]
> Hey @RohitRajendran 👋🏼 this should now be fully rolled out. If you manually install the Next.js Runtime then you will need to update via NPM, otherwise the latest version should install during your next build. Thanks again for the PR!

Thanks!! Got it working! 🙌🏽

**Pull request merged**
